#==========================================================================
# https://github.com/ophub/kernel
# Description: Delete older releases and workflows runs
#==========================================================================

name: Delete older releases and workflows

on:
  repository_dispatch:
  workflow_call:
  workflow_dispatch:
    inputs:
      del_workflows:
        description: "Delete workflows records?"
        required: true
        default: true
        type: boolean
      workflows_keep_day:
        description: "Days to keep workflows."
        required: false
        default: 15
        type: choice
        options:
          - 30
          - 20
          - 15
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0
      workflows_keep_keyword:
        description: "keywords for keep workflows."
        required: false
        default: ""
      out_log:
        description: "Output detailed JSON logs."
        required: false
        default: true
        type: boolean

env:
  TZ: Etc/UTC

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    env:
      DEL_WORKFLOWS: ${{ inputs.del_workflows || true }}
      WORKFLOWS_KEEP_DAY: ${{ inputs.workflows_keep_day || 15 }}
      WORKFLOWS_KEEP_KEYWORD: ${{ inputs.workflows_keep_keyword }}
      OUT_LOG: ${{ inputs.out_log || true }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: false
          delete_tags: false
          delete_workflows: ${{ env.DEL_WORKFLOWS }}
          workflows_keep_day: ${{ env.WORKFLOWS_KEEP_DAY }}
          workflows_keep_keyword: ${{ env.WORKFLOWS_KEEP_KEYWORD }}
          out_log: ${{ env.OUT_LOG }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
